import { Inter } from "next/font/google";
import "./globals.css";
import { CustomNavbar } from "../components/navbar.js";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <CustomNavbar />
        {children}
        <footer>Next Quiz © 2024</footer>
      </body>
    </html>
  );
}
